# Generated by Django 3.2.9 on 2021-12-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentDegree', models.FloatField(default=13)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellingPortal.student')),
            ],
        ),
    ]
